export const TEMTEMS = {
  Mimit: { types: ['Digital'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 1, spatk: 0, spdef: 1 } },
  Oree: { types: ['Digital'], tv: { hp: 0, sta: 1, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Zaobian: { types: ['Digital'], tv: { hp: 0, sta: 2, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Chromeon: { types: ['Digital'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Halzhi: { types: ['Digital'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Molgu: { types: ['Digital'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Platypet: { types: ['Water', 'Toxic'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 1, spdef: 0 } },
  Platox: { types: ['Water', 'Toxic'], tv: { hp: 0, sta: 0, spd: 1, atk: 0, def: 0, spatk: 1, spdef: 0 } },
  Platimous: { types: ['Water', 'Toxic'], tv: { hp: 0, sta: 0, spd: 2, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Swali: { types: ['Nature'], tv: { hp: 0, sta: 1, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Loali: { types: ['Nature', 'Wind'], tv: { hp: 0, sta: 1, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Tateru: { types: ['Neutral'], tv: { hp: 0, sta: 2, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Gharunder: { types: ['Toxic', 'Electric'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 2 } },
  Mosu: { types: ['Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 1, spdef: 0 } },
  Magmut: { types: ['Melee', 'Fire'], tv: { hp: 3, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Paharo: { types: ['Wind'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Paharac: { types: ['Wind'], tv: { hp: 1, sta: 0, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Granpah: { types: ['Wind'], tv: { hp: 0, sta: 0, spd: 2, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Ampling: { types: ['Electric'], tv: { hp: 0, sta: 0, spd: 2, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Amphatyr: { types: ['Electric', 'Nature'], tv: { hp: 0, sta: 0, spd: 4, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Bunbun: { types: ['Earth', 'Crystal'], tv: { hp: 0, sta: 0, spd: 2, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Mudrid: { types: ['Earth', 'Crystal'], tv: { hp: 0, sta: 0, spd: 3, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Hidody: { types: ['Nature'], tv: { hp: 0, sta: 2, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Taifu: { types: ['Nature'], tv: { hp: 0, sta: 2, spd: 0, atk: 0, def: 0, spatk: 1, spdef: 0 } },
  Fomu: { types: ['Water'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 2 } },
  Wiplump: { types: ['Water', 'Wind'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Skail: { types: ['Neutral'], tv: { hp: 0, sta: 0, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Skunch: { types: ['Neutral', 'Melee'], tv: { hp: 1, sta: 0, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Goty: { types: ['Neutral'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 1, spdef: 0 } },
  Mouflank: { types: ['Neutral'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 1, spatk: 0, spdef: 0 } },
  Rhoulder: { types: ['Neutral', 'Earth'], tv: { hp: 2, sta: 0, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Houchic: { types: ['Mental'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 1, spdef: 0 } },
  Tental: { types: ['Mental'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Nagaise: { types: ['Mental', 'Water'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 3, spdef: 0 } },
  Orphyll: { types: ['Nature', 'Toxic'], tv: { hp: 0, sta: 0, spd: 2, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Nidrasil: { types: ['Nature', 'Toxic'], tv: { hp: 0, sta: 0, spd: 0, atk: 3, def: 0, spatk: 0, spdef: 0 } },
  Banapi: { types: ['Fire'], tv: { hp: 0, sta: 0, spd: 2, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Capyre: { types: ['Fire'], tv: { hp: 0, sta: 0, spd: 2, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Lapinite: { types: ['Crystal'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 2, spatk: 0, spdef: 0 } },
  Azuroc: { types: ['Crystal'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 3, spatk: 0, spdef: 0 } },
  Zenoreth: { types: ['Crystal'], tv: { hp: 2, sta: 0, spd: 0, atk: 0, def: 2, spatk: 0, spdef: 0 } },
  Reval: { types: ['Mental'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 3, spdef: 0 } },
  Aohi: { types: ['Mental', 'Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 3, spdef: 1 } },
  Bigu: { types: ['Nature'], tv: { hp: 0, sta: 2, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Babawa: { types: ['Nature', 'Water'], tv: { hp: 0, sta: 4, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  '0b1': { types: ['Digital', 'Electric'], tv: { hp: 0, sta: 1, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  '0b10': { types: ['Digital', 'Electric'], tv: { hp: 0, sta: 2, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Kaku: { types: ['Nature'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Saku: { types: ['Nature', 'Wind'], tv: { hp: 2, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Valash: { types: ['Neutral', 'Crystal'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 2, spdef: 0 } },
  Towly: { types: ['Melee', 'Mental'], tv: { hp: 0, sta: 0, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Owlhe: { types: ['Wind', 'Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Barnshe: { types: ['Wind', 'Mental'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 1, spdef: 0 } },
  Gyalis: { types: ['Crystal', 'Melee'], tv: { hp: 0, sta: 0, spd: 4, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Occlura: { types: ['Crystal'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 1 } },
  Myx: { types: ['Crystal', 'Mental'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 3, spdef: 0 } },
  Raiber: { types: ['Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 1, spatk: 0, spdef: 0 } },
  Raize: { types: ['Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 2, spatk: 0, spdef: 0 } },
  Raican: { types: ['Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 2, spatk: 2, spdef: 0 } },
  Pewki: { types: ['Water'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Piraniant: { types: ['Water'], tv: { hp: 2, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Scarawatt: { types: ['Electric'], tv: { hp: 2, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Scaravolt: { types: ['Electric', 'Fire'], tv: { hp: 3, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Hoglip: { types: ['Digital', 'Fire'], tv: { hp: 0, sta: 0, spd: 1, atk: 0, def: 0, spatk: 1, spdef: 0 } },
  Hedgine: { types: ['Digital', 'Fire'], tv: { hp: 0, sta: 0, spd: 2, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Osuchi: { types: ['Earth'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Osukan: { types: ['Earth', 'Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 3, def: 0, spatk: 0, spdef: 0 } },
  Osukai: { types: ['Earth', 'Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 4, def: 0, spatk: 0, spdef: 0 } },
  Saipat: { types: ['Water', 'Melee'], tv: { hp: 3, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Pycko: { types: ['Earth', 'Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 1, spdef: 0 } },
  Drakash: { types: ['Earth', 'Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 3, spdef: 0 } },
  Crystle: { types: ['Crystal'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 2, spatk: 0, spdef: 0 } },
  Sherald: { types: ['Crystal'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 3, spatk: 0, spdef: 0 } },
  Tortenite: { types: ['Crystal', 'Toxic'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 3, spatk: 2, spdef: 0 } },
  Innki: { types: ['Electric', 'Crystal'], tv: { hp: 0, sta: 1, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Shaolite: { types: ['Melee'], tv: { hp: 0, sta: 0, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 1 } },
  Shaolant: { types: ['Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 2 } },
  Cycrox: { types: ['Digital', 'Toxic'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Hocus: { types: ['Mental'], tv: { hp: 0, sta: 0, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Pocus: { types: ['Mental'], tv: { hp: 0, sta: 0, spd: 2, atk: 0, def: 0, spatk: 1, spdef: 0 } },
  Smolzy: { types: ['Electric'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Sparzy: { types: ['Electric'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Golzy: { types: ['Electric', 'Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 3, def: 0, spatk: 0, spdef: 0 } },
  Mushi: { types: ['Toxic'], tv: { hp: 0, sta: 0, spd: 2, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Mushook: { types: ['Toxic', 'Melee'], tv: { hp: 0, sta: 0, spd: 2, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Magmis: { types: ['Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Mastione: { types: ['Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 3, def: 0, spatk: 0, spdef: 0 } },
  Umishi: { types: ['Water'], tv: { hp: 0, sta: 0, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Ukama: { types: ['Water'], tv: { hp: 0, sta: 1, spd: 2, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Galvanid: { types: ['Electric'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Raignet: { types: ['Electric'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Smazee: { types: ['Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Baboong: { types: ['Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 3, def: 0, spatk: 0, spdef: 0 } },
  Seismunch: { types: ['Melee', 'Earth'], tv: { hp: 0, sta: 0, spd: 2, atk: 3, def: 0, spatk: 0, spdef: 0 } },
  Zizare: { types: ['Earth'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 3, spatk: 0, spdef: 0 } },
  Gorong: { types: ['Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 4, spatk: 0, spdef: 0 } },
  Mitty: { types: ['Mental'], tv: { hp: 0, sta: 0, spd: 0, atk: 3, def: 0, spatk: 0, spdef: 0 } },
  Sanbi: { types: ['Mental'], tv: { hp: 0, sta: 0, spd: 0, atk: 3, def: 1, spatk: 0, spdef: 0 } },
  Momo: { types: ['Neutral'], tv: { hp: 0, sta: 0, spd: 3, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Kuri: { types: ['Earth'], tv: { hp: 0, sta: 1, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Kauren: { types: ['Earth'], tv: { hp: 2, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Spriole: { types: ['Nature'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 1, spatk: 0, spdef: 0 } },
  Deendre: { types: ['Nature'], tv: { hp: 2, sta: 0, spd: 0, atk: 0, def: 1, spatk: 0, spdef: 0 } },
  Cerneaf: { types: ['Nature'], tv: { hp: 2, sta: 0, spd: 0, atk: 0, def: 2, spatk: 0, spdef: 0 } },
  Toxolotl: { types: ['Toxic'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Noxolotl: { types: ['Toxic'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 2 } },
  Blooze: { types: ['Toxic'], tv: { hp: 2, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Goolder: { types: ['Toxic'], tv: { hp: 4, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Zephyruff: { types: ['Toxic', 'Wind'], tv: { hp: 0, sta: 0, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Volarend: { types: ['Toxic', 'Wind'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 3 } },
  Grumvel: { types: ['Earth'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Grumper: { types: ['Earth', 'Electric'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Ganki: { types: ['Electric', 'Wind'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Gazuma: { types: ['Electric', 'Wind'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Oceara: { types: ['Water'], tv: { hp: 0, sta: 0, spd: 1, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Yowlar: { types: ['Neutral'], tv: { hp: 3, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Droply: { types: ['Water', 'Earth'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Garyo: { types: ['Water', 'Earth'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Broccoblin: { types: ['Nature'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 1 } },
  Broccorc: { types: ['Nature', 'Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Broccolem: { types: ['Nature', 'Melee'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Shuine: { types: ['Crystal', 'Water'], tv: { hp: 0, sta: 3, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Nessla: { types: ['Water', 'Electric'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 2 } },
  Valiar: { types: ['Mental'], tv: { hp: 0, sta: 2, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Pupoise: { types: ['Digital', 'Nature'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Loatle: { types: ['Digital', 'Mental'], tv: { hp: 2, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Kalazu: { types: ['Water'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 1, spatk: 0, spdef: 0 } },
  Kalabyss: { types: ['Water', 'Toxic'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 2, spatk: 0, spdef: 0 } },
  Adoroboros: { types: ['Toxic', 'Mental'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 4 } },
  Tuwai: { types: ['Wind'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Tukai: { types: ['Wind', 'Water'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 3 } },
  Tulcan: { types: ['Wind', 'Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 3, spdef: 0 } },
  Tuvine: { types: ['Wind', 'Crystal'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 4, spatk: 0, spdef: 0 } },
  Turoc: { types: ['Wind', 'Earth'], tv: { hp: 4, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Tuwire: { types: ['Wind', 'Digital'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Tutsu: { types: ['Wind', 'Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 4, def: 0, spatk: 0, spdef: 0 } },
  Kinu: { types: ['Nature', 'Mental'], tv: { hp: 0, sta: 4, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Vulvir: { types: ['Fire', 'Earth'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 0 } },
  Vulor: { types: ['Fire', 'Earth'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 1, spatk: 0, spdef: 0 } },
  Vulcrane: { types: ['Fire', 'Earth'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 2, spatk: 0, spdef: 0 } },
  Pigepic: { types: ['Wind'], tv: { hp: 0, sta: 1, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 1 } },
  Akranox: { types: ['Earth', 'Toxic'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 1, spdef: 0 } },
  Koish: { types: ['Water'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Vulffy: { types: ['Earth', 'Nature'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 3 } },
  Chubee: { types: ['Digital', 'Wind'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 1, spatk: 0, spdef: 0 } },
  Waspeen: { types: ['Digital', 'Crystal'], tv: { hp: 3, sta: 0, spd: 0, atk: 0, def: 2, spatk: 0, spdef: 0 } },
  Mawtle: { types: ['Digital', 'Nature'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 1 } },
  Mawmense: { types: ['Digital', 'Nature'], tv: { hp: 3, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 1 } },
  Hazrat: { types: ['Toxic', 'Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 4, def: 0, spatk: 0, spdef: 0 } },
  Minttle: { types: ['Mental'], tv: { hp: 0, sta: 0, spd: 0, atk: 1, def: 0, spatk: 0, spdef: 0 } },
  Minox: { types: ['Mental', 'Electric'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Minothor: { types: ['Mental', 'Electric'], tv: { hp: 1, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 0 } },
  Maoala: { types: ['Melee', 'Mental'], tv: { hp: 0, sta: 1, spd: 0, atk: 3, def: 0, spatk: 0, spdef: 0 } },
  Venx: { types: ['Neutral'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 0, spatk: 0, spdef: 2 } },
  Venmet: { types: ['Neutral', 'Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 2, def: 2, spatk: 0, spdef: 0 } },
  Vental: { types: ['Neutral', 'Mental'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 2 } },
  Chimurian: { types: ['Nature', 'Crystal'], tv: { hp: 0, sta: 0, spd: 1, atk: 0, def: 0, spatk: 0, spdef: 2 } },
  Arachnyte: { types: ['Neutral', 'Digital'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 3, spdef: 0 } },
  Thaiko: { types: ['Digital', 'Melee'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Monkko: { types: ['Digital', 'Melee'], tv: { hp: 2, sta: 0, spd: 0, atk: 0, def: 0, spatk: 2, spdef: 0 } },
  Anahir: { types: ['Crystal', 'Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 2, spatk: 0, spdef: 2 } },
  Anatan: { types: ['Crystal', 'Fire'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 3, spatk: 0, spdef: 2 } },
  Tyranak: { types: ['Fire', 'Nature'], tv: { hp: 1, sta: 0, spd: 0, atk: 0, def: 0, spatk: 0, spdef: 1 } },
  Volgon: { types: ['Electric'], tv: { hp: 0, sta: 0, spd: 0, atk: 0, def: 0, spatk: 4, spdef: 0 } },
};
